feat(esl-utils): JS based ability to block container scroll
exadel-inc/esl pull request #1051
Opened 2022-06-21 13:33 UTC by fshovchko

In the scope of this PR added:
- Ability to lock scroll on the element;
- Ability to remove scroll lock on the element;
- Ability to check if the element has a scroll lock on it.
- Includes #1056: Make ScrollUtils functional, rework API

2022-06-21 23:52 UTC, ala-n requested changes

2022-06-21 23:52 UTC, ala-n commented on src/modules/esl-scrollbar/core/esl-scrollbar.ts
> +import {ScrollUtils} from '../../all';
Please do not use massive cumulative bundles in the bounds of the library.
We can not guarantee that the final consumers will have tree shaking optimization working.

2022-06-21 23:52 UTC, ala-n commented on src/modules/esl-utils/dom/scroll/utils.ts
> +    return target.hasAttribute('esl-js-scroll-lock') && targetMap.has(target);
Why do we have to check a double marker here ?

2022-06-21 23:52 UTC, ala-n commented on src/modules/esl-utils/dom/scroll/utils.ts
> +  }
That's fine and it almost works (if we do not include artifacts that come from the scroll passive event nature in the modern browsers)
But there is a problem with the main goal of this issue:
The business's purpose was to create a mechanism that allows us to lock user manipulations but let us scroll the container via JS (the ScrollTo enhancement story...).

2022-06-29 12:24 UTC, dshovchko commented on src/modules/esl-utils/dom/scroll/utils.ts
> +    document.body.removeAttribute('esl-scroll-lock');
It looks like toggleBodyScrollLock() function. We can replace also the same code in lockScroll() with toggleBodyScrollLock() and avoid repeating code.

2022-07-03 12:17 UTC, ala-n commented
**NOTE**: Requested to be merged with squash

2022-07-06 09:26 UTC, dshovchko approved these changes

2022-07-06 10:34 UTC, julia-murashko approved these changes

2022-07-06 10:34 UTC, julia-murashko commented on src/modules/esl-utils/dom/scroll/utils.ts
> +/** Check if element is blocked from scrolling */
```suggestion
/** Checks if element is blocked from scrolling */
```

2022-07-06 10:34 UTC, julia-murashko commented on src/modules/esl-utils/dom/scroll/utils.ts
> +/** Check vertical scroll based on content height */
```suggestion
/** Checks vertical scroll based on content height */
```

2022-07-06 10:34 UTC, julia-murashko commented on src/modules/esl-utils/dom/scroll/utils.ts
> + * Enable scroll on the target element in case it was requested with given initiator.
```suggestion
 * Enables scroll on the target element in case it was requested with given initiator.
```

2022-07-06 10:39 UTC, abarmina approved these changes

2022-07-06 10:43 UTC, NastaLeo commented on src/modules/esl-utils/dom/scroll/utils.ts
> +   * - 'none' | null | undefined - totally lock scroll with `overflow: hidden` option
```suggestion
   * - 'none' | null | undefined - totally locks scroll with `overflow: hidden` option
```

2022-07-06 10:43 UTC, NastaLeo approved these changes

2022-07-06 12:05 UTC, ala-n approved these changes

2022-07-06 12:33 UTC, merged

2022-07-08 18:55 UTC, ala-n commented
:tada: This PR is included in version 4.0.0-beta.10 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0-beta.10)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0-beta.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-04 23:58 UTC, ala-n commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: