feat(esl-utils): extend SynteticEventTarget with ability to separate events enhancement
exadel-inc/esl pull request #1118
Opened 2022-07-22 11:29 UTC by fshovchko

In the scope of this PR I extended SynteticEventTarget to separate events by their type.
The end result repeats implementation of native event storage.
Code base tests were extended and refactored.

2022-07-27 10:04 UTC, dshovchko approved these changes

2022-07-29 01:13 UTC, ala-n requested changes

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    }
```suggestion
    if (typeof type !== 'string') return this,addEventListener('change', type);
```

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    }
+ the same trick in the `hasEventListener` method

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +  public addEventListener(type: string | EventListenerOrEventListenerObject = 'change', callback?: EventListenerOrEventListenerObject): void {
```suggestion
  public addEventListener(type: string | EventListenerOrEventListenerObject, callback?: EventListenerOrEventListenerObject): void {
```
Method does not have empty argument definition

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    }
```suggestion
  public removeEventListener(type: string | EventListenerOrEventListenerObject, callback?: EventListenerOrEventListenerObject): void {
    if (typeof type !== 'string') return this.removeEventListener('change', type);
```

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    this.hasEventListener(type) ? listeners.push(callback!) : Object.assign(this._listeners, {[type]: [callback!]});
```suggestion
    if (this._listeners[type] && !this._listeners[type].includes(callback!)) this._listeners[type].push(callback!)
    else Object.assign(this._listeners, {[type]: [callback!]});
```

2022-07-29 01:13 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    if (cbIndex > -1) listeners.splice(cbIndex, 1);
Cosmetic: 
```suggestion
    if (!this._listeners[type]) return;
    this._listeners[type] = this._listeners[type].filter((cb) => cb !== callback)
```

2022-07-31 22:19 UTC, ala-n commented on src/modules/esl-utils/dom/events/target.ts
> +    this.hasEventListener(type) ? listeners.push(callback!) : Object.assign(this._listeners, {[type]: [callback!]});
The current implementation accepts a single listener to be subscribed multiple times, but it's unacceptable as this fact may used by the consumers.

2022-08-01 12:27 UTC, julia-murashko approved these changes

2022-08-01 14:05 UTC, NastaLeo approved these changes

2022-08-01 16:30 UTC, yadamskaya approved these changes

2022-08-01 16:34 UTC, abarmina approved these changes

2022-08-02 01:21 UTC, ala-n approved these changes

2022-08-02 01:23 UTC, merged

2022-08-02 21:56 UTC, ala-n commented
:tada: This PR is included in version 4.0.0-beta.13 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0-beta.13)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0-beta.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-04 23:57 UTC, ala-n commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: