Refactor/svg refactor
exadel-inc/esl pull request #1139
Opened 2022-08-09 08:05 UTC by Natalie-Smirnova

- Examples index page:  SVG representation picture on the page was updated, the draft pages partially transparent on the index page was made ,  badges were added.
- Core and Components index page:  the grid style was replaced with the list style, badges were added.
- The list item UI was updated : badges were added, white background,  icons on hover, two columns view 
![image](https://user-images.githubusercontent.com/55104823/183596402-d1e8c029-a683-4264-a3b9-671f21d15b14.png)
![image](https://user-images.githubusercontent.com/55104823/183597028-2d1f7246-6d61-4e83-827c-56ba0a749f2b.png)
![list](https://user-images.githubusercontent.com/55104823/183597350-cf67814b-f0d2-4f5c-8498-69ee2704da59.gif)
![examples](https://user-images.githubusercontent.com/55104823/183597717-7eb05d2c-f00b-4809-9141-a343f3bcf8b3.gif)

2022-08-10 01:27 UTC, ala-n commented on pages/views/core/esl-utils.njk
> +icon: 'common/right-arrow.svg'
It looks like we don't need to set this information to pages directly, it is common styling

2022-08-10 01:27 UTC, ala-n commented on pages/static/assets/sidebar/components.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21.625 6.5H2.375A1.377 1.377 0 0 1 1 5.125v-2.75C1 1.617 1.617 1 2.375 1h19.25C22.383 1 23 1.617 23 2.375v2.75c0 .758
It looks like it's better to remove `fill="none"` as well as we have no icon on preview in editors, which is not good

2022-08-10 01:27 UTC, ala-n commented on pages/src/collection-grid/collection-grid.less
> +    }
I'd recommend to replace arrow SVG with a CSS alternative with a pseudo-element and border embedded svg

2022-08-10 02:07 UTC, ala-n requested changes

2022-08-10 02:07 UTC, ala-n commented on pages/views/components/esl-select-list.njk
> +icon: 'common/right-arrow.svg'
And also, an important note we definitely don't want to have an icon of example to be presented in the title on the page

2022-08-11 00:56 UTC, ala-n reviewed
Looks cool!
Just a couple of last cosmetic suggestions:
1) Make a draft badge red on collections pages
2) As for me, it's better to render the draft badge in a list view in addition to opacity

2022-08-11 00:56 UTC, ala-n commented on pages/views/_layouts/content.njk
> +          {% if icon and not aside %}{% include "static/assets/" + icon %}{% endif %}
`aside` is not a good criterion to define if we need an icon, 
As a suggestion, try to rename icon assets for samples pages to `preview` then we will not have a conflict with that meta fields

2022-08-11 15:48 UTC, ala-n approved these changes

2022-08-11 15:48 UTC, ala-n commented on pages/views/_layouts/content.njk
> +          {% if preview %}{% include "static/assets/" + preview %}{% endif %}
Sorry but the `preview` for the icon looks strange, I meant that we could rename the field for examples collection.
If we are going to change that field, we can consider `sectionIcon`,  `collectionIcon`, or smth like that

2022-08-12 12:56 UTC, fshovchko commented on pages/src/collection-grid/collection-grid.less
> +
```suggestion
```

2022-08-12 12:56 UTC, fshovchko commented on pages/src/collection-grid/collection-grid.less
> +  }
```suggestion
    opacity: 30%;
  }
```

2022-08-14 22:30 UTC, ala-n commented
TODO will be moved to a separate request.
Merging this update with squash

2022-08-14 22:32 UTC, merged

2022-08-15 13:14 UTC, ala-n commented
:tada: This PR is included in version 4.0.0-beta.14 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0-beta.14)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0-beta.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-04 23:57 UTC, ala-n commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: