fix(esl-panel-group): change `no-animate` API
exadel-inc/esl pull request #1155
Opened 2022-08-16 14:34 UTC by NastaLeo

Part of [#1132](https://github.com/exadel-inc/esl/issues/1132)

2022-08-16 19:01 UTC, ala-n requested changes

2022-08-16 19:01 UTC, ala-n commented on src/modules/esl-panel-group/core/esl-panel-group.ts
> +    return !ESLMediaQuery.for(this.noAnimate);
```suggestion
    return !ESLMediaQuery.for(this.noAnimate).matches;
```

2022-08-16 20:06 UTC, NastaLeo commented on src/modules/esl-panel-group/core/esl-panel-group.ts
> +    return !ESLMediaQuery.for(this.noAnimate);
Thanks!

2022-08-16 21:01 UTC, ala-n approved these changes

2022-08-17 11:09 UTC, yadamskaya approved these changes

2022-08-17 13:29 UTC, julia-murashko approved these changes

2022-08-17 14:57 UTC, merged

2022-08-30 15:34 UTC, ala-n commented
:tada: This PR is included in version 4.0.0-beta.15 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0-beta.15)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0-beta.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-04 23:57 UTC, ala-n commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.0.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: