fix(esl-scrollbar): change target on `window` for `scroll` event
exadel-inc/esl pull request #1349
Opened 2022-11-25 11:11 UTC by Natalie-Smirnova

Fixed scroll when the target is  'html' 

Closes: #1338

2022-11-25 14:47 UTC, ala-n requested changes

2022-11-25 14:47 UTC, ala-n commented on src/modules/esl-scrollbar/core/esl-scrollbar.ts
> +      this.$$on({event: 'scroll', target: window}, this._onScrollOrResize);
```suggestion
      this.$$on({event: ''resize scroll'', target: window}, this._onScrollOrResize);
```
According to initial metainformation on this._onScrollOrResize

2022-11-26 01:18 UTC, ala-n commented
Looks like 
```@listen({event: 'resize scroll', passive: true, auto: false})```
meta declaration on `_onScrollOrResize` is no longer required:
passive is controlled by the ESL listener itself,
auto: false required only for marked methods to maintain them manually
events are covered on subscription instructions

2022-11-26 01:18 UTC, ala-n approved these changes

2022-11-28 10:05 UTC, NastaLeo approved these changes

2022-11-28 10:53 UTC, julia-murashko approved these changes

2022-11-28 12:44 UTC, fshovchko approved these changes

2022-11-28 19:51 UTC, dshovchko approved these changes

2022-11-28 20:44 UTC, abarmina approved these changes

2022-11-29 23:20 UTC, merged

2022-12-09 09:55 UTC, ala-n commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.1.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: