Extend esl-related-target mixin
exadel-inc/esl pull request #1398
Opened 2023-01-09 14:01 UTC by Natalie-Smirnova

- was made related target able to target multiple related togglable
- was introduced `esl-related-target-action` with  `'hide'|'show'|'all'(default)` as a values

Closes: #427

2023-01-11 03:01 UTC, ala-n approved these changes

2023-01-11 08:42 UTC, yadamskaya approved these changes

2023-01-11 08:42 UTC, yadamskaya commented on build/jest.html-loader.js
> +      code: `module.exports = ${JSON.stringify(sourceText)};`,
minor
```suggestion
      code: `module.exports = ${JSON.stringify(sourceText)};`
```

2023-01-11 21:15 UTC, dshovchko approved these changes

2023-01-11 21:15 UTC, dshovchko commented on build/jest.html-loader.js
> +  },
```suggestion
  }
```

2023-01-11 21:15 UTC, dshovchko commented on src/modules/esl-related-target/core/esl-related-target.ts
> +    this.$targets.forEach(target => target.show({params: this.mergeParams(params)}));
```suggestion
    this.$targets.forEach((target) => target.show({params: this.mergeParams(params)}));
```

2023-01-11 21:15 UTC, dshovchko commented on src/modules/esl-related-target/core/esl-related-target.ts
> +    this.$targets.forEach(target => target.hide({params: this.mergeParams(params)}));
```suggestion
    this.$targets.forEach((target) => target.hide({params: this.mergeParams(params)}));
```

2023-01-12 08:59 UTC, NastaLeo commented on pages/views/examples/accordion.njk
> +    <h2>Simple multiple accordion (panels 1 and 1.3 contain esl-related-target attribute)</h2>
```suggestion
    <h2>Simple multiple accordion (panel 1 contains esl-related-target attribute)</h2>
```

2023-01-12 09:00 UTC, NastaLeo commented on src/modules/esl-related-target/README.md
> +To make cross-reference (bidirectional binding) of toggleables you need to cross-reference both of the tooglables:
```suggestion
To make cross-reference (bidirectional binding) of toggleables you need to cross-reference both of the toogleables:
```

2023-01-12 09:13 UTC, NastaLeo approved these changes

2023-01-12 20:28 UTC, ala-n requested changes
Example updated to the real use-case
PR rejected as esl-related-target doesn't work on the real case (see added nested accordion example)

2023-01-12 20:29 UTC, ala-n commented on src/modules/esl-related-target/core/esl-related-target.ts
> +    const targets = ESLTraversingQuery.all(selector);
Incorrect usage of Traversing Query base element is missing to support relative pathes

2023-01-12 20:41 UTC, ala-n approved these changes

2023-01-16 12:31 UTC, abarmina approved these changes

2023-01-16 12:31 UTC, abarmina commented on pages/views/examples/accordion.njk
> +    {#    {% endcode %} #}
do we need these comments?

2023-01-17 02:22 UTC, merged

2023-02-02 23:20 UTC, ala-n commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.2.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: