feat(esl-utils): Support for ESLDomElementTarget as a target for ESLResizeObserverTarget
exadel-inc/esl pull request #1573
Opened 2023-03-27 14:38 UTC by fshovchko

Target for ResizeObserverTarget with extended from 'Element' to being able to accept mixin elements.  #1562

2023-03-27 23:20 UTC, ala-n requested changes

2023-03-27 23:20 UTC, ala-n commented on src/modules/esl-event-listener/core/targets/resize.adapter.ts
> +    const host = getPropertyDescriptor(target, '$host') as Element;
How does the property descriptor relate to the host value ? 
Is it not compatible;e with Element, and it is not something that the ESLResizeObserverTarget observer should use.

2023-03-29 13:04 UTC, ala-n commented on src/modules/esl-event-listener/core/targets/resize.adapter.ts
> +    if (!(target instanceof Window || target instanceof Element)) target = target.$host;
Consider mowing to esl-utils/abstract/dom-target as utility `resolveDomTarget`
That can also be applied to other cases of ESLDomElementTarget usage

2023-03-29 13:04 UTC, ala-n commented on src/modules/esl-event-listener/core/targets/resize.adapter.ts
> +export type ESLResizeTarget = ESLDomElementTarget | Window;
Consider removing it due to only one actual usage, and no practical need for users as well

2023-03-29 22:04 UTC, ala-n requested changes
This was not an exception to creating tasks regarding ESLElementRelated and window separately.

The first one relates to creating `resolveDomTarget` basically, and it will most likely be reused 
It will be a simple change for ESLResizeObserverTarget but it relates to 
 - discussion of the `resolveDomTarget` function usage, name and etc.
 
 The second issue regarding window is a completely different story, we need to think about unified API. And it also has a chance to be even rejected.

2023-04-11 00:55 UTC, ala-n approved these changes

2023-04-11 08:36 UTC, NastaLeo approved these changes

2023-04-12 16:58 UTC, merged

2023-04-12 18:42 UTC, ala-n commented
:tada: This PR is included in version 4.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.4.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: