fix(esl-utils): debounced unhandled rejection
exadel-inc/esl pull request #1839
Opened 2023-07-28 14:11 UTC by fshovchko

The scope of this PR is to fix the issue described in #1801, and to refactor code from a function to a class

closes #1801

2023-07-28 19:27 UTC, ala-n requested changes
Please consider an alternative approach:
 - do not change debounce (most likely, at all). A similar issue may appear in other async decorators
 - Make the `Deferred` utility improved with a lazy `<instanceof Deferred>.promise` instead
 
 The original request to make a class was related to `Defered` but not a denounced.
 
 Please also provide tests to make sure we have no problem (ideally, first of all, make a unit test cases and make sure they are correct but not successful, and then provide a fix)

2023-07-29 15:04 UTC, ala-n commented on src/modules/esl-utils/async/test/promise/defered.test.ts
>    });
Consider the following list of expectation (draft):
```suggestion
  test('Resolve of Deferred produces resolved promise', () => {
    const def$$ = createDeferred();
    def$$.resolve(1);
    return def$$.promise.then((n) => expect(n).toBe(1));
  });
  test('Rejected Deferred produces rejected promise', () => {
    const def$$ = createDeferred();
    def$$.reject(1);
    return def$$.promise.catch((n) => expect(n).toBe(1));
  });

  test('Deferred resolves initially requested promise when resolved', () => {
    const def$$ = createDeferred();
    +def$$.promise;
    def$$.resolve(1);
    return def$$.promise.then((n) => expect(n).toBe(1));
  });
  test('Deferred rejects initially requested promise when rejected', () => {
    const def$$ = createDeferred();
    +def$$.promise;
    def$$.reject(1);
    return def$$.promise.catch((n) => expect(n).toBe(1));
  });

  describe('Rejected Deferred does not leads to uncaught in promise', () => {
    const throwFn = jest.fn((reason) => {throw reason;});
    beforeAll(() => {
      // Avoid memory leak by adding too many listeners
      process.env.LISTENING_TO_UNHANDLED_REJECTION = String(true);
      process.on('unhandledRejection', throwFn);
    });
    afterAll(() => {
      process.off('unhandledRejection', throwFn);
    });
    test('Deferred does not leads to uncaught', async () => {
      const def$$ = createDeferred();
      def$$.reject(1);
      await promisifyTimeout(0);
      expect(throwFn).not.toBeCalled();
    });
  });
```

2023-08-07 08:43 UTC, julia-murashko approved these changes

2023-08-07 15:36 UTC, yadamskaya approved these changes

2023-08-08 07:11 UTC, HenadzV approved these changes

2023-08-08 07:19 UTC, NastaLeo commented on src/modules/esl-utils/async/promise/defered.ts
> +/** A deferred object represents promise with it's resolve/reject methods */
why instead of its it's?

2023-08-08 07:19 UTC, NastaLeo approved these changes

2023-08-08 09:40 UTC, dshovchko approved these changes

2023-08-08 16:00 UTC, merged