feat(esl-media): create `lazy` attribute
exadel-inc/esl pull request #1854
Opened 2023-08-08 21:22 UTC by Natalie-Smirnova

Closes: 

Relates to:

2023-08-09 22:01 UTC, ala-n commented on src/modules/esl-media/README.md
> + - `disabled` (boolean) - marker that prevents media api initialization. Deprecated alias for *manual* mode of `lazy` attribute
TODO: please check indents and correct rendering on the [GitHub](https://github.com/exadel-inc/esl/blob/esl-media-support-lazy-initialization/src/modules/esl-media/README.md) and first of all on the related site page

2023-08-21 18:37 UTC, dshovchko approved these changes

2023-08-21 18:37 UTC, dshovchko commented on src/modules/esl-media/core/esl-media.ts
> +        }
In order to reduce the complexity of the method, can we put this code in a separate method, for example, `onLazyAttributeChange()`?

2023-08-21 18:37 UTC, dshovchko commented on src/modules/esl-media/core/esl-media-iobserver.ts
> +  // Remove `lazy` attribute when media is in viewport with min ratio RATIO_TO_ACTIVATE
```suggestion
  // Removes `lazy` attribute when media is in the viewport with min ratio RATIO_TO_ACTIVATE
```

2023-08-28 11:20 UTC, NastaLeo approved these changes

2023-08-29 15:40 UTC, ala-n requested changes
Please check the following points:
 - `<esl-media lazy ...` or `<esl-media lazy="blabla">` shod be considered as lazy = 'auto'
 - Please add at least one example to check lazy, for example make the background video examples on the embedded-video page lazy
 - As for now, the lazy loading seems to be not working the video on the page does not load at the moment of lazy attribute removal

2023-09-20 20:35 UTC, ala-n requested changes
⛔ live tests are not passed: the `esl-media` instances are not lazy.

2023-09-21 13:08 UTC, ala-n approved these changes
✅ Live Tests are passed no additional requests from my side

2023-09-21 13:30 UTC, dshovchko approved these changes

2023-09-21 16:40 UTC, NastaLeo approved these changes

2023-09-21 22:04 UTC, abarmina commented on src/modules/esl-media/test/esl-media.lazy.test.ts
> +  test('ESLMedia is not loading when lazy atrribute is set', async () => {
```suggestion
  test('ESLMedia is not loading when lazy attribute is set to manual', async () => {
```

2023-09-21 22:12 UTC, abarmina approved these changes

2023-09-22 11:12 UTC, julia-murashko approved these changes

2023-09-22 14:14 UTC, merged

2023-09-22 15:53 UTC, ala-n commented
:tada: This PR is included in version 4.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.12.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: