refactor(esl-event-listener): event`s `type` is now replaced with `TYPE`
exadel-inc/esl pull request #2344
Opened 2024-04-16 11:53 UTC by fshovchko

2024-04-16 13:16 UTC, ala-n requested changes

2024-04-16 13:16 UTC, ala-n commented on site/src/esl-events-demo/esl-wheel-demo/esl-wheel-demo-area.ts
> +    this.log({name, TYPE, data: {axis, deltaX, deltaY}});
Same here

2024-04-16 18:03 UTC, ala-n approved these changes

2024-04-16 21:07 UTC, abarmina approved these changes

2024-04-16 22:35 UTC, merged

2024-04-20 15:17 UTC, ala-n commented
:tada: This PR is included in version 5.0.0-beta.14 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/5.0.0-beta.14)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v5.0.0-beta.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-05-31 14:23 UTC, ala-n commented
:tada: This PR is included in version 4.17.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.17.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: