Feature/[ESL Alert] Introduce new ESL Alert component
exadel-inc/esl pull request #5
Opened 2021-01-12 12:30 UTC by julia-murashko

2021-01-12 15:56 UTC, ala-n requested changes

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +  onTriggerHandler(e: CustomEvent) {
Cosmetic: naming. onRequest / onControlEvent or smth like that

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +      const params = Object.assign({}, {hideDelay: 2500}, e.detail, {force: true});
Magic number in the method is not good, mb we can introduce "Default" constant somewhere?

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +  iframe.className = 'ie-zindex-fix';
There is no such style in ESL right now

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +  public defaultParams: AlertActionParams;
Feature Request: There is no possibility for the final consumer to setup default without inheritance to introduce a modified component.
mb let's try to move defaultValue to the static object then.

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.less
> +esl-alert {
Do this style super abstract?
We can not rely on consumer X here, We should define something really abstract for consuming.

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +    this.text.className = 'hpe-alert-text';
Really really bed class name!

2021-01-12 15:56 UTC, ala-n commented on src/modules/esl-alert/core/esl-alert.ts
> +  @attr({defaultValue: ''}) public cls: string;
???
Class is a CSS class that will be added via CSSUtility but not a type attribute that we use in a prototype.

2021-01-12 15:58 UTC, ala-n commented
Also full code documentation.
And separately or with this PR documentation README.

2021-01-14 12:16 UTC, ala-n approved these changes

2021-01-14 12:30 UTC, yadamskaya approved these changes

2021-01-14 14:22 UTC, merged

2021-01-18 19:55 UTC, ala-n commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: