docs: fix footer style
exadel-inc/esl pull request #608
Opened 2021-11-01 14:06 UTC by Anna-MariiaPetryk

# PR Details

Footer component bugfixes

2021-11-01 14:26 UTC, ala-n requested changes

2021-11-01 14:26 UTC, ala-n commented on pages/views/_includes/footer.njk
> +      <a href="{{ site.github.url }}" target="_blank">
`class` can be added to a tag

2021-11-01 14:26 UTC, ala-n commented on pages/views/_includes/footer.njk
> +    </div>
something wrong here
- no classes on anchors
- single footer-link for two anchors

2021-11-01 14:26 UTC, ala-n commented on pages/src/footer/footer.less
> +  &-github{
Can be abstract '&-social-link' or '&-icon-link'

2021-11-02 16:58 UTC, ala-n requested changes

2021-11-02 16:58 UTC, ala-n commented on pages/src/footer/footer.less
> +    height: 55  px;
```suggestion
    height: 55px;
```
Extra spaces, that may cause an issues

2021-11-02 16:58 UTC, ala-n commented on pages/src/footer/footer.less
> +  &-accordion-trigger[aria-expanded="true"]{
Do not use aria attribute in the styles!!
Aria attributes only consumes the state of component but they should not deliver it

2021-11-02 16:58 UTC, ala-n commented on pages/views/_includes/footer-menu.njk
> +    <div class="footer-accordion-title footer-accordion-arrow {{ 'nav-item-selected' if collection in page.url }}" href="#">
`href` is not presented on the div tag

2021-11-03 14:49 UTC, ala-n approved these changes

2021-11-03 16:05 UTC, dshovchko approved these changes

2021-11-03 18:41 UTC, abarmina approved these changes

2021-11-03 19:25 UTC, merged

2021-11-15 23:39 UTC, ala-n commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/3.5.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: