feat(esl-traversing-query): add ability to restrict global scope
exadel-inc/esl pull request #639
Opened 2021-11-15 14:34 UTC by Anna-MariiaPetryk

# PR Details

## Description

## Related Issue

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-11-18 02:30 UTC, ala-n requested changes

2021-11-18 02:30 UTC, ala-n commented on src/modules/esl-traversing-query/core/esl-traversing-query.ts
> +    if (scope === null) throw new Error();
In case we throw an error - there is no reason to allow null value at all

2021-11-18 02:30 UTC, ala-n commented on src/modules/esl-traversing-query/core/esl-traversing-query.ts
> +    if (scope === null) throw new Error();
I'd recommend restricting type and getting rid of an error (the user will have it anyway if he passed a null)
From an API point of view, we are also do not allow undefined or null scope, it is the required field for TraversingQuery
`base` element accepts null just for the purpose of being searched using query without base, e.g. queries like `#id::next` and etc.

2021-11-21 20:10 UTC, ala-n approved these changes

2021-11-22 10:23 UTC, yadamskaya approved these changes

2021-11-22 10:26 UTC, julia-murashko approved these changes

2021-11-22 11:29 UTC, dshovchko approved these changes

2021-11-23 01:31 UTC, merged

2021-11-28 20:35 UTC, ala-n commented
:tada: This PR is included in version 3.7.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/3.7.0-beta.1)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v3.7.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-07 23:57 UTC, ala-n commented
:tada: This PR is included in version 3.8.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/3.8.0-beta.1)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v3.8.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-10 01:21 UTC, ala-n commented
:tada: This PR is included in version 3.8.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/3.8.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v3.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: