docs: rtl-switcher-component
exadel-inc/esl pull request #650
Opened 2021-11-17 16:29 UTC by fshovchko

# PR Details

## Description

## Related Issue

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

2021-11-17 16:47 UTC, dshovchko commented on pages/src/rtl-switcher/rtl-switcher.ts
> +export class ESLDemoSwitcher extends ESLBaseElement {
It looks like it should have ESLDemoRTLSwitcher name.

2021-11-17 16:47 UTC, dshovchko commented on pages/src/rtl-switcher/rtl-switcher.ts
> +    console.log(this.$target?.dir);
Missed debug

2021-11-17 16:47 UTC, dshovchko commented on pages/src/rtl-switcher/rtl-switcher.ts
> +    const isActive = this.$target?.dir === 'rtl' ? true : false;
Can be simplified

```suggestion
    const isActive = this.$target?.dir === 'rtl';
```

And also it can be moved to separated getter.

2021-11-17 16:47 UTC, dshovchko commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  public ltrDirection() {
It is better that the name of the methods begin with a verb.

2021-11-17 16:47 UTC, dshovchko commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  public rtlDirection() {
The same.

2021-11-18 02:22 UTC, ala-n requested changes

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +import {TraversingQuery} from '../../../src/modules/all';
`import {TraversingQuery} from '../../../src/modules/esl-traversing-query/core';`
+ move to other imports

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  }
```suggestion
  public get $target(): HTMLElement | undefined {
    return this._$target;
  }
```
Use the strict types, please

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  protected _$target: any;
Use strict types please

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  public set $target(newPopupInstance) {
Strict types as linter check says

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +    this.bindEvents();
It's better to bing and unbind event in connected/disconnected callback and have a check for an existent target in event handler action

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  public get $active(): any {
Incorrect notation active is not an HTML Element

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  }
Can be simplified there is no reason to have so many sub-methods for a simple action.

2021-11-18 02:22 UTC, ala-n commented on pages/src/rtl-switcher/rtl-switcher.ts
> +  }
You can convert it to a single method with a boolean term isRTLTargetDirection as a base

2021-11-18 02:22 UTC, ala-n commented on pages/views/introduction/index.njk
> +<esl-d-rtl-switcher target="::next"></esl-d-rtl-switcher>
Please, use exact target pages like tabs examples.
We can not have a temporary version with not ready or incorrectly placed content in the main branch.

2025-04-08 15:02 UTC, ala-n commented
CLosed as implemented on UIP project side

2025-04-08 15:02 UTC, closed without merging