feat(esl-toggleable): add auto id
exadel-inc/esl pull request #746
Opened 2021-12-28 14:29 UTC by NastaLeo

Add auto id to ESLToggleable component (will set if there isn't user's id).
User can also disable auto id.

2021-12-29 01:37 UTC, ala-n requested changes

2021-12-29 01:37 UTC, ala-n commented on src/modules/esl-toggleable/README.md
> + - `no-auto-id` - Not to allow auto id
```suggestion
 - `no-auto-id` - Disallow automatic id creation when it's empty
```

2021-12-29 01:37 UTC, ala-n commented on src/modules/esl-toggleable/core/esl-toggleable.shape.ts
> +  /** Disable auto id */
```suggestion
  /** Disallow automatic id creation when it's empty */
```

2021-12-29 01:37 UTC, ala-n commented on src/modules/esl-toggleable/core/esl-toggleable.ts
> +  /** Not to allow auto id */
```suggestion
  /** Disallow automatic id creation when it's empty */
```

2021-12-29 01:37 UTC, ala-n commented on src/modules/esl-toggleable/core/esl-toggleable.ts
> +      this.id = sequentialUID(ESLToggleable.is, 'esl-toggleable-');
```suggestion
      const tag = this.constructor.is;
      this.id = sequentialUID(tag, tag + '-');
```

2021-12-29 01:40 UTC, ala-n commented
@NastaLeo it will be ideal if you update the previous commit with the more detailed comment (to simplify release process):
`feat(esl-togglable): add id auto-creation feature for toggleable instances`

2021-12-29 10:35 UTC, abarmina approved these changes

2021-12-29 12:49 UTC, ala-n approved these changes

2021-12-29 13:27 UTC, julia-murashko approved these changes

2021-12-29 16:37 UTC, dshovchko approved these changes

2021-12-30 07:09 UTC, merged

2022-01-12 21:30 UTC, ala-n commented
:tada: This PR is included in version 3.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/3.11.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v3.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: