feat(esl-utils): Transition duration utility
exadel-inc/esl pull request #821
Opened 2022-02-07 20:42 UTC by fshovchko

In the scope of this PR I added a utility to get a transition length

2022-02-07 23:24 UTC, ala-n requested changes
To be discussed on tomorrow's call.

We should have a utility to resolve a class of problems but not specific ones. (But you are really close to making this code universal btw)
Also, the esl-utils can be extended only with unit tests provided for extending, until it's not agreed with a @exadel-inc/esl-core-team.

2022-02-08 13:42 UTC, ala-n commented
> To be discussed on tomorrow's call.
> 
> We should have a utility to resolve a class of problems but not specific ones. (But you are really close to making this code universal btw) Also, the esl-utils can be extended only with unit tests provided for extending, until it's not agreed with a @exadel-inc/esl-core-team.

````
/** @example parseTime('.5s') // 500 */
function parseTime(timeStr: string): number;

/** @example parseTimeSet('.5s, 1ms') // [500, 1] */
function parseTimeSet(timeStr: string): number[];
```

2022-02-09 11:45 UTC, ala-n approved these changes

2022-02-09 11:45 UTC, ala-n commented on src/modules/esl-utils/misc/format.ts
> +    return parseNumber(timeStr, NaN)!;
Just `+timeStr` is enough in our situation.
Also, it looks like we need to fix a little bit types for `parseNumber` method

2022-02-09 11:45 UTC, ala-n commented on src/modules/esl-utils/misc/format.ts
> +    return parseNumber(timeStr, NaN)!;
There is also a coulee minor points (regarding `parseTime('2wtf') // NaN but not 2000`)

2022-02-09 14:09 UTC, dshovchko commented on src/modules/esl-utils/misc/test/format.test.ts
> +      [['1024ms'], 1024],
I suggest adding test cases for these values:
4.s
350.ms
Look like these is invalid values.

2022-02-10 14:19 UTC, dshovchko approved these changes

2022-02-11 18:53 UTC, NastaLeo approved these changes

2023-11-20 13:32 UTC, NastaLeo commented on src/modules/esl-utils/misc/format.ts
> +  const isMilliseconds = timeStr.indexOf('ms') !== -1;
const value = parseFloat(timeStr);
  const isMilliseconds = timeStr.trim().endsWith('ms');
  return value * (isMilliseconds ? 1 : 1000);

2023-11-20 17:15 UTC, dshovchko approved these changes

2023-11-20 18:10 UTC, NastaLeo approved these changes

2023-11-21 10:13 UTC, julia-murashko approved these changes

2023-11-22 11:43 UTC, abarmina approved these changes

2023-11-22 11:51 UTC, merged

2023-11-24 15:43 UTC, ala-n commented
:tada: This PR is included in version 4.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@exadel/esl/v/4.14.0)
- [GitHub release](https://github.com/exadel-inc/esl/releases/tag/v4.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: